[package]
name = "nextcore-tool"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
plist = "1.10"
nextcore-core = { git = "https://github.com/26x86/Nextcore-Core.git", rev = "f4b921206dfff2b51449eb7b7b03200f07b445b4" }
nextcore-apls = { git = "https://github.com/26x86/Nextcore-APLS.git", rev = "1d7c330186ceb4a62dd48259b2f0af7525844315" }
